### ISSUE TITLE
MQTT port

### ISSUE THREAD

**Issue by wire-samara** [VGCH/power_counter_ha#1]
Проект хороший. У самого такой счетчик.
Но нет выбора порта mqtt сервера.
У Home Assistant по умолчанию 1883.
Можно добавить во вкладку "Кофигурация передачи данных (MQTT)" выбор порта?

**Comment by VGCH** [comment]
Добрый день, спасибо за предложение. Скорректирую код, но порт нужно будет указывать при указании адреса сервера, например 192.168.10.25:1883

**Comment by VGCH** [comment]
Изменил код, теперь можно изменять порт подключения  к  MQTT серверу.
